### PR TITLE
fix apache default path

### PR DESCRIPTION
**Pull request by om3rcitak**

### CODE REVIEW

**Comment by pensiero** [comment]
Hi @Om3rCitak, thanks for your PR. I usually use "public" in my projects, and I prefer not to override this file when I setup a project.
BUT I didn't think that other people could have different needs.

So, what about replacing `public` with an environment variable, like `PROJECT_PATH `? In this way we can easily change it.

The final result would be `DocumentRoot ${PROJECT_PATH}/${PROJECT_PUBLIC_PATH}`.

What do you think about it?

**Comment by om3rcitak** [comment]
`DocumentRoot ${PROJECT_PATH}/${PROJECT_PUBLIC_PATH} ` nice idea.
I selected ${PROJECT_PATH}/${PROJECT_PUBLIC_PATH} from all options :)

**Comment by pensiero** [comment]
Resolved with a separate commit, as agreed: https://github.com/pensiero/dockerfile-apache-php/commit/3da36c1912c70533226910e18e3a49f7856aa737

**Comment by pensiero** [comment]
@Om3rCitak please note I changed the name into `PROJECT_PUBLIC_DIR`

**Pull request closed without merging**
